services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DB}" ]
        interval: 10s
        timeout: 3s
        retries: 5

    restart: unless-stopped

  app:
    build:
      context: ./backend
    ports:
      - '8080:8080'
    networks:
      - default
    environment:
      SERVER_PORT: 8080
      POSTGRES_JDBC_URL: ${POSTGRES_JDBC_URL}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://0.0.0.0:8080/actuator/health' ]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '8001:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.route-prefix=/prometheus'
      - '--web.external-url=http://0.0.0.0:9090/prometheus/'
    healthcheck:
      test: [ 'CMD', 'wget', '-q', '-O', '-', 'http://0.0.0.0:9090/prometheus/-/healthy' ]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - 'prometheus-data:/prometheus'
      - './backend/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  grafana:
    image: grafana/grafana-enterprise
    depends_on:
      prometheus:
        condition: service_healthy
    environment:
      GF_SERVER_ROOT_URL: http://0.0.0.0:3000/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: true
    ports:
      - '8002:3000'
    volumes:
      - 'grafana-data:/var/lib/grafana'
      - './backend/config/grafana/provisioning:/etc/grafana/provisioning:ro'
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://0.0.0.0:3000/api/health' ]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  frontend:
    environment:
      VITE_API_URL: ${VITE_API_URL}
    build:
      context: ./frontend
    ports:
      - '3000:80'
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped


volumes:
  postgres-data:
  grafana-data:
  prometheus-data:
